Delete .Rhistory
I got an error when trying to pull that said 
error: The following untracked working tree files would be overwritten by merge:
	.Rhistory
Please move or remove them before you can merge.
So I thought I'd try removing it, since there didn't seem to be anything in it.